name: Ejecutar Pipeline en cada Push

on:
  push:
    branches:
      - main  # O la rama que usas

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt 

      - name: Ejecutar pipeline
        run: python extract.py

      - name: Notificación
        run: echo "Pipeline ejecutado con éxito 🚀"
