name: Ejecutar Pipeline en cada Push

on:
  push:
    branches:
      - main  # O la rama que usas

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt 

      - name: Instalar Jupyter
        run: pip install jupyter nbconvert

      - name: Ejecutar el notebook
        run: jupyter nbconvert --execute --to notebook --inplace Project.ipyn

      - name: Notificación
        run: echo "Pipeline ejecutado con éxito 🚀"
